name: SDK Publish NPM
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm i
      - name: Tests
        run: npm run test
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: master
      - name: Build
        run: npm run build:prod
      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}